### ISSUE TITLE
Algorithm Writeup

### ISSUE THREAD

**Issue by danman113** [ProbableTrain/MapGenerator#19]
Hey, thanks for publishing the source code for this, it's super informative.

I was wondering if you could do a high-level writeup of how everything works, from the algorithm you use to generate the streets to path generation to rendering. I understand that you use a Tensor Field to determine the orientation of the streets, but everything that happens after you click `generate` is a bit of a black box without looking through the source code.

If that's too much effort then even a few links to outside resources would be super helpful.

Thanks!

**Comment by ProbableTrain** [comment]
I'll get on it

**Comment by ProbableTrain** [comment]
I've created a documentation site [here](https://maps.probabletrain.com/), will be adding implementation details soon
