### ISSUE TITLE
Building height selection and skyscrapers.

### ISSUE THREAD

**Issue by HugoCortell** [ProbableTrain/MapGenerator#50]
Im not sure if the building height can be tweaked to be honest, maybe I just missed something, I think id be cool to have the option to select a range at which most buildings will scale.

And maybe even an option for "skyscrapers", the same way in which theres a percentage selector for which buildings will be grouped up into one big block, there should be a percentage that are wayyy taller than the rest.

Its easy enough to do a few skyscrapers in blender, but a built-in option for greater variation to all buildings would be nice.

**Comment by HugoCortell** [comment]
Not sure how to mark this as suggestion

**Comment by ProbableTrain** [comment]
One idea I had was to divide the city into areas e.g. residential, commercial, industrial (cities skylines anyone?) and use that to inform building attributes such as density, footprint size, building heights etc - currently it's either a normal or gaussian distribution between preset values.

One issue is that the 3D building effect is 'faked' - there's no 3D renderer acting, it naively draws building sides first, then rooves. This is fine-ish when building heights are similar, but as soon as there's a skyscraper the illusion breaks down (you'd be able to see the rooves of adjacent buildings through the walls of the skyscraper).
